services:
  - type: web
    name: nilecare-chat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PINECONE_API_KEY
        value: your-pinecone-key
      - key: OPENAI_API_KEY
        value: your-openai-key
