services:
  - type: web
    name: NileCare-ChatBot
    env: python
    runtime: python
    repo: https://github.com/na09git/NileCare-ChatBot
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
