services:
  - type: web
    name: nilecare-chatbot
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: PINECONE_API_KEY
        value: your-pinecone-api-key
    plan: free
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: gunicorn app:app
